name: Deploy Documentation to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive
          persist-credentials: false

    - name: Install C++ Prerequisites
      shell: bash
      run: |
        sudo apt install cmake g++ python3-dev libboost-all-dev

    - name: Set up Conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.8

    - name: Install Python Prerequisites
      run: |
        python -m pip install --upgrade pip
        conda install cartopy shapely
        pip install setuptools wheel twine sphinx sphinx_rtd_theme

    - name: Build and Install
      shell: bash
      run: pip install .

    - name: Make Documentation
      shell: bash
      working-directory: docs
      run: make html

    - name: Deploy to Pages
      uses: JamesIves/github-pages-deploy-action@3.6.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/_build/html # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
