# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Install C++ Prerequisites
      shell: bash
      run: |
        sudo apt install cmake g++ python3-dev libboost-all-dev

    - name: Set up Conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.8

    - name: Install Python Prerequisites
      run: |
        python -m pip install --upgrade pip
        conda install cartopy shapely
        pip install setuptools wheel twine sphinx sphinx_rtd_theme

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
